#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx

echo -e "location /redirect_me {\n    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n" > /etc/nginx/sites-available/default

/etc/init.d/nginx restart
ps aux | grep nginx | grep -v grep > /dev/null

if [ $? -eq 0 ]; then
    echo "Nginx installed and configured for redirection!"
else
    echo "Error: Nginx installation or configuration failed."
fi
