#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
MyConfig="\
frontend annie_frontend
    bind *:80
    stats uri /haproxy?stats
    default_backend web-servers
    
backend annie_backend
    balance roundrobin
    server 5292-web-01 3.85.54.66:80
    server 5292-web-02 54.221.178.27:80
"
sudo apt-get update
sudo apt-get install -y haproxy
echo "$MyConfig" | sudo tee -a
/etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a
/etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
