#!/bin/bash

# Function to handle cleanup
cleanup() 
{
    echo "Deleting PID file and terminating script."
    rm -f /var/run/myscript.pid
    exit 0
}

# Trap signals and associate them with the cleanup function
trap 'cleanup' SIGQUIT SIGTERM

# Function to handle SIGINT signal
sigint_handler() 
{
    echo "Y U no love me?!"
}

# Trap SIGINT and associate it with the sigint_handler function
trap 'sigint_handler' SIGINT

# Function to handle SIGTERM signal
sigterm_handler() 
{
    echo "I hate the kill command"
}

# Trap SIGTERM and associate it with the sigterm_handler function
trap 'sigterm_handler' SIGTERM

# Get the current process ID and save it to the PID file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
echo "To infinity and beyond"
while true; do
    sleep 1
done

