#!/usr/bin/env bash
# This script is displaying the content the content of a current directory

file_path="school"

# Check if the file exists
if [ -e "$file_path" ]; then
    echo "school file exists"

    if [ -s "$file_path" ]; then
        echo "school file is not empty"

        if [ -f "$file_path" ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi

